/*
 * Copyright (c) 2020 The ZMK Contributors
 *
 * SPDX-License-Identifier: MIT
 */
#pragma once

#define MS_LOG 0
#define MS_RESET 1

#define MS_TP_SENSITIVITY_INCR 10
#define MS_TP_SENSITIVITY_DECR 11

#define MS_TP_NEG_INERTIA_INCR 12
#define MS_TP_NEG_INERTIA_DECR 13

#define MS_TP_VALUE6_INCR 14
#define MS_TP_VALUE6_DECR 15

#define MS_TP_PTS_THRESHOLD_INCR 16
#define MS_TP_PTS_THRESHOLD_DECR 17

#define MS_TP_UP_THRESH_INCR 18
#define MS_TP_UP_THRESH_DECR 19

#define MS_TP_Z_TIME_INCR 20
#define MS_TP_Z_TIME_DECR 21

#define MS_TP_JENKS_CURV_INCR 22
#define MS_TP_JENKS_CURV_DECR 23

#define MS_TP_DRAG_HYSTERESIS_INCR 24
#define MS_TP_DRAG_HYSTERESIS_DECR 25

#define MS_TP_MIN_DRAG_INCR 26
#define MS_TP_MIN_DRAG_DECR 27

#define MS_TP_REACH_INCR 28
#define MS_TP_REACH_DECR 29
